[package]
name = "areacodes"
version = "0.1.0"
authors = ["Scallop Ye"]
edition = "2021"
default-run = "areacodes"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
